import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <div className={styles.container}>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy my physical NFTs</h1>
        <div className={styles.grid}>
          <div style={{margin : '1rem'}}>
            <Image
              src="/Images/A.jpeg"
              alt="NFT"
              width={300}
              height={300}
            />
            <p>Very expensive art piece 1</p>
            
          </div>
          <div style={{margin : '1rem'}}>
            <Image
              src="/Images/B.jpeg"
              alt="NFT"
              width={300}
              height={300}
            />
            <p>Very expensive art piece 2</p>
          </div>
        </div>
      </main>
    </div>
    </>
  )
}
